name: oticon
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=22.3.1
  - python=3.11
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch
    - torchvision
    - torchaudio
    - black
    - numpy
    - matplotlib
    - ipykernel
    - ipywidgets
    - scipy
    - scikit-learn
    - tqdm
