name: oticon
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - black
    - numpy
    - matplotlib
    - ipykernel
    - ipywidgets
    - scipy
    - scikit-learn
    - tqdm
    - wandb
